In [2]:
import random
import numpy as np
import pandas as pd


# Define a string with a value equal to “Python is fun!”. Print every third character of this string.

In [84]:
a = "Python is fun!"
print(a[2:len(a):3])

tnsu


# Create three list variables named 'StudentName', 'ID', and 'EmailAddress'. Add 5 random values in these lists and print them.

In [16]:
def generateStr(letters, length):
    return "".join(random.choice(letters) for i in range(length))

alphabet = 'abcdefghijklmnopqrstuvwxyz'
numbers = '0123456789'
StudentName = []
ID = []
EmailAddress = []

for i in range(5):
    StudentName.append(generateStr(alphabet, random.choice(range(4,10))))
    ID.append(StudentName[i][:2] + (generateStr(numbers, 6)))
    EmailAddress.append(StudentName[i][:3] + '.' + generateStr(alphabet, 5) + '@' + generateStr(alphabet, 8) + '.com')
    
print(StudentName)
print(ID)
print(EmailAddress)

['vvgtczj', 'ihusymoi', 'mwdz', 'iwivs', 'ldvmpv']
['vv701665', 'ih076246', 'mw743332', 'iw870354', 'ld543403']
['vvg.bufqo@bvgegxgm.com', 'ihu.aqvee@njgsuumn.com', 'mwd.jiltb@vegujcan.com', 'iwi.cybsd@elkhgcbl.com', 'ldv.oolpm@xzwxnlpa.com']


# Create a dictionary variable with three keys, which are named same as the list created in the previous problem. Insert the previously created lists in the dictionary variable and print it.

In [22]:
StudentDict = {}
StudentDict['Name'] = StudentName
StudentDict['ID'] = ID
StudentDict['Email'] = EmailAddress
print(StudentDict)

{'Name': ['vvgtczj', 'ihusymoi', 'mwdz', 'iwivs', 'ldvmpv'], 'ID': ['vv701665', 'ih076246', 'mw743332', 'iw870354', 'ld543403'], 'Email': ['vvg.bufqo@bvgegxgm.com', 'ihu.aqvee@njgsuumn.com', 'mwd.jiltb@vegujcan.com', 'iwi.cybsd@elkhgcbl.com', 'ldv.oolpm@xzwxnlpa.com']}


#  Define a numeric variable 'energy' and assign value either 1 or 2. Print "Apple" if the value of energy variable is 1 otherwise print "Banana". What will your program print if energy=10? 

In [27]:
def checkEnergy(energy):
    print(energy)
    if energy == 1:
        print('Apple' + '\n')
    else:
        print('Banana' + '\n')

energy = random.choice([1,2])
checkEnergy(energy)
energy = 10
checkEnergy(energy)

1
Apple

10
Banana



#  Print numbers between 0 and 2000 separated by line, which are divisible by 5.

In [31]:
for i in range(2001):
    if i % 5 == 0 and i != 0:
        print(i)

5
10
15
20
25
30
35
40
45
50
55
60
65
70
75
80
85
90
95
100
105
110
115
120
125
130
135
140
145
150
155
160
165
170
175
180
185
190
195
200
205
210
215
220
225
230
235
240
245
250
255
260
265
270
275
280
285
290
295
300
305
310
315
320
325
330
335
340
345
350
355
360
365
370
375
380
385
390
395
400
405
410
415
420
425
430
435
440
445
450
455
460
465
470
475
480
485
490
495
500
505
510
515
520
525
530
535
540
545
550
555
560
565
570
575
580
585
590
595
600
605
610
615
620
625
630
635
640
645
650
655
660
665
670
675
680
685
690
695
700
705
710
715
720
725
730
735
740
745
750
755
760
765
770
775
780
785
790
795
800
805
810
815
820
825
830
835
840
845
850
855
860
865
870
875
880
885
890
895
900
905
910
915
920
925
930
935
940
945
950
955
960
965
970
975
980
985
990
995
1000
1005
1010
1015
1020
1025
1030
1035
1040
1045
1050
1055
1060
1065
1070
1075
1080
1085
1090
1095
1100
1105
1110
1115
1120
1125
1130
1135
1140
1145
1150
1155
1160
1165
1170
1175
1180
1185
1190
1195
1200
1205
1210
1215
1220

# Is it possible to break a loop before executing for the defined number of iterations? If yes, provide an example using While loop structure. Otherwise, explain your answer (why and how).  

In [38]:
# this loop will continue iterating until the value of a equals 5
# if it was impossible to break the loop it would continue 
# forever
while True:
    a = random.choice(range(10))
    print(a)
    if a == 5:
        break

9
3
7
6
1
9
0
5


# Create a function with two input parameters say (x, y) and return output values by doing operations such as 'x+y' and 'x-y'. Call the function with (4,7) and print the outputs.

In [40]:
def function(x, y):
    return x % y

print(function(4, 7))

4


# Create and display a 3X3 Identity matrix and multiply it with a 3x4 Random matrix.

In [45]:
a = np.identity(3)
b = np.random.randint(0, 100, (3, 4))

print(a)
print(b)
print(np.matmul(a, b))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[36 47 51 86]
 [62 77 54 18]
 [52 85 19 86]]
[[36. 47. 51. 86.]
 [62. 77. 54. 18.]
 [52. 85. 19. 86.]]


# Create a 5x2 matrix, initialise with random values and print it. Now, transpose the matrix and print it. How the transposed matrix is different from original matrix? 

In [49]:
a = np.random.randint(0,100, (5,2))
print(a)
b = np.transpose(a)
print(b)

# a transposed matrix swaps each row in the original matrix to a coresponding column turning a 5x2 matrix into a 2x5 matrix

[[ 3  5]
 [ 6 71]
 [51 46]
 [41 56]
 [51 88]]
[[ 3  6 51 41 51]
 [ 5 71 46 56 88]]


#  Read the data stored in the "data.csv" file as a matrix. The row of the matrix represents data point or instance and the column represents the variable or feature. Print the number of data instances and variables present in this dataset. Calculate mean of the second variable and deduct this mean from original values of the variable. Print both original and modified values of the variable.

In [3]:
data = pd.read_csv('data.csv', header=None)
dataFrame = pd.DataFrame(data)
finalArray = np.array(dataFrame.values)

print('number of data point: ' + str(len(finalArray)))
print('number of variable: ' + str(len(finalArray[0])))

totalVar = 0
for i in finalArray:
    print(i[1])
    totalVar += i[1]

avg = totalVar/len(finalArray)

modList = []
for i in finalArray:
    modList.append(i[1] - avg)

print('\n')

for i in modList:
    print(i)

         0       1
0   3.3816  3.3891
1   4.5279  5.8542
2   2.6557  4.4120
3   2.7652  3.7154
4   2.8466  4.1755
5   3.8907  6.4884
6   3.4758  3.6328
7   5.9113  6.6808
8   3.9289  5.0984
9   4.5618  5.6233
10  4.5741  5.3977
11  4.3717  5.4612
12  4.1917  4.9547
13  5.2441  4.6615
14  2.8358  3.7680
15  5.6353  6.3121
16  4.6863  5.6652
17  2.8505  4.6265
18  5.1102  7.3632
19  5.1826  4.6465
20  5.7073  6.6810
21  3.5797  4.8028
22  5.6394  6.1204
23  4.2635  4.6894
24  2.5365  3.8845
25  3.2238  4.9426
26  4.9295  5.9550
27  5.7930  5.1084
28  2.8168  4.8190
29  3.8888  5.1004
30  3.3432  5.8930
31  5.8797  5.5214
32  3.1039  3.8571
33  5.3315  4.6807
34  3.3754  4.5654
35  4.7767  6.2544
36  2.6757  3.7310
37  5.5003  5.6795
38  1.7971  3.2475
39  4.3225  5.1111
40  4.4210  6.0256
41  3.1793  4.4369
42  3.0335  3.9788
43  4.6093  5.8798
44  2.9638  3.3002
45  3.9718  5.4077
46  1.1802  2.8787
47  1.9190  5.0711
48  3.9552  4.5053
49  5.1180  6.0851
number of data point: 50
number